install:
  - choco install -y InnoSetup

build_script:
  - gradlew.bat :ui:jfxNative --stacktrace

# to run your custom scripts instead of automatic tests
test_script:
  - gradlew.bat checkstyleMain checkstyleTest pmdMain jacocoTestReport jacocoRootReport test --stacktrace -Pheadless=true -PlogTests

platform:
  - x64

artifacts:
  - path: ui\build\jfx\native\*.exe


deploy:
  provider: GitHub
  description: ''
  auth_token:
      secure: k0uhlsYxGoZkHVNNm4E+WnOiBfzsv4yLS+htlplR7JwzARqiAC2RU0cVnsIg1UF0
  artifact: /.*\.exe/           # upload all exe packages to release assets
  draft: true
  prerelease: true
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only

cache:
  - C:\Users\appveyor\.gradle
